baseurl = "http://kenmhaggerty.com/blog/"
languageCode = "en-us"
title = "Blog • Ken M. Haggerty"
theme = "angels-ladder"

[Params]
home = "http://kenmhaggerty.com"
twitter = "kenmhaggerty"
github = "kenmhaggerty"
showsRSS = true
copyright = "Written by Ken M. Haggerty • 2016"
cover = "hero.png"
thumbnail = "thumbnail.png"
